### ISSUE TITLE
Somehow this extension turned into a adware

### ISSUE THREAD

**Issue by marcocorriero** [FallenMax/chrome-extension-allow-copy#1]
I installed for awhile  , idk how then misterious ads came up, even reset my chrome, scanned, nothing.

Soo i decided to disable each extension until ads were gone...

When i disabled this extension, the ads stopped appearing!

This extension is a adware...

**Comment by marcocorriero** [comment]
Nevermind, it was a virus somehow injected into this extension his code, all sorted, i had just to remove then reinstall this extension. Maybe add a verify system to check if this extension has been modified or not?

**Comment by FallenMax** [comment]
Thank you for reporting!  Please make sure ONLY install extensions from Chrome Store: https://chrome.google.com/webstore/detail/simple-allow-copy/aefehdhdciieocakfobpaaolhipkcpgc
