### ISSUE TITLE
Allow us to see the list of sites that it remembers

### ISSUE THREAD

**Issue by garyking** [FallenMax/chrome-extension-allow-copy#2]
Please allow us to see the list of sites that this extension remembers, for the pages that it auto-enables.

Or at least, where can I find the list of sites, in any of the Chrome profile files?

**Comment by FallenMax** [comment]
@garyking Hi, the list is stored in Chrome locally (with [Storage API](https://developer.chrome.com/extensions/storage)).

It's not exposed to user. But you can access the list in following steps:

1. Right click on Simple Allow Copy's browser icon, click "Manage Extension"
2. Click "Background Page", it will open an DevTool window
3. In DevTool window, enter `chrome.storage.local.get(null, console.log)` and press <kbd>Enter</kbd>, it will print everything this extension has stored. 

Hope this can help you.

**Comment by garyking** [comment]
I click on "Manage Extensions" on this extension, and it opens the URL: chrome://extensions/?id=aefehdhdciieocakfobpaaolhipkcpgc

When I try the command on that page, I get the error:

```
Uncaught TypeError: Cannot read property 'local' of undefined
    at <anonymous>:1:16
```
