### ISSUE TITLE
It breaks almost all the ajax functions on any Discuz! forums

### ISSUE THREAD

**Issue by fireattack** [FallenMax/chrome-extension-allow-copy#3]
[Discuz!](https://www.discuz.net/) is a popular forum engine used in Chinese communities. 

This extension, even when not enabled, will break almost all the AJAX callbacks on such forum. That includes quick reply, add bookmark, give scores, etc. basically any interactive functions.

A typical error would be 

```
common.js?aB7:691 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at HTMLIFrameElement.handleResult (common.js?aB7:691)
```

(this particular file is at https://www.tsdm.live/static/js/common.js?aB7 )

Unfortunately I currently can't find a way to demonstrate it without having account on such forum.

**Comment by FallenMax** [comment]
Sorry but I don't think it's relevant. Try disable the extension on these sites?

**Comment by fireattack** [comment]
It happens even when the extension is not enabled (greyed out).

The problem is the code injected by the extension breaks these sites.
